const questionnaire = [
  {
    id: "projectName",
    label: "Project name",
    type: "text",
    placeholder: "Clinic CRM",
    required: true,
    helpText: "Used to label the generated plan and downloadable files.",
  },
  {
    id: "projectStage",
    label: "Project stage",
    type: "select",
    required: true,
    options: ["idea", "prototype", "mvp", "growing-product"],
    helpText: "Helps balance simplicity against future scalability.",
  },
  {
    id: "businessType",
    label: "Business type",
    type: "select",
    required: true,
    options: [
      "saas",
      "e-commerce",
      "marketplace",
      "social-platform",
      "internal-system",
      "content-platform",
      "fintech",
      "healthcare",
      "edtech",
    ],
    helpText: "Different products map to different architectural patterns.",
  },
  {
    id: "targetRegion",
    label: "Target region",
    type: "select",
    required: true,
    options: ["north-america", "europe", "asia", "global"],
    helpText: "Used for cost multipliers and service availability notes.",
  },
  {
    id: "deploymentPreference",
    label: "Deployment preference",
    type: "select",
    required: true,
    options: ["managed-cloud", "self-managed-cloud", "hybrid", "on-premise"],
    helpText: "Guides hosting and managed-service recommendations.",
  },
  {
    id: "monthlyUsers",
    label: "Estimated monthly users",
    type: "number",
    required: true,
    min: 0,
    helpText: "Primary signal for scale and traffic estimates.",
  },
  {
    id: "monthlyBudget",
    label: "Monthly infrastructure budget (USD)",
    type: "number",
    required: true,
    min: 0,
    helpText: "Constrains architecture complexity and provider choice.",
  },
  {
    id: "applicationType",
    label: "Application type",
    type: "select",
    required: true,
    options: [
      "web-app",
      "mobile-app",
      "integrated-system",
      "dbms-platform",
      "api-platform",
      "iot-platform",
    ],
    helpText: "Defines how many delivery surfaces the system should support.",
  },
  {
    id: "coreFeatures",
    label: "Core features",
    type: "multiselect",
    required: true,
    options: [
      "authentication",
      "payments",
      "subscription-billing",
      "file-upload",
      "search",
      "analytics-dashboard",
      "reporting",
      "team-collaboration",
      "third-party-integrations",
      "workflow-automation",
      "admin-panel",
      "notifications",
    ],
    helpText: "Each selected feature adds architecture components.",
  },
  {
    id: "realtimeFeatures",
    label: "Needs realtime features",
    type: "boolean",
    required: true,
    helpText: "Adds websocket or pub/sub components when necessary.",
  },
  {
    id: "dataSensitivity",
    label: "Data sensitivity",
    type: "select",
    required: true,
    options: ["low", "medium", "high"],
    helpText: "Shapes security, backups, and access controls.",
  },
  {
    id: "availabilityRequirement",
    label: "Availability requirement",
    type: "select",
    required: true,
    options: ["basic", "important", "critical"],
    helpText: "Affects monitoring, redundancy, and failover strategy.",
  },
  {
    id: "expectedGrowth",
    label: "Expected growth",
    type: "select",
    required: true,
    options: ["slow", "moderate", "fast", "unpredictable"],
    helpText: "Generates the migration roadmap.",
  },
  {
    id: "teamTechnicalLevel",
    label: "Team technical level",
    type: "select",
    required: true,
    options: ["low", "medium", "high"],
    helpText: "Prevents overengineering for less technical teams.",
  },
  {
    id: "needFastDelivery",
    label: "Need fast MVP delivery",
    type: "boolean",
    required: true,
    helpText: "Biases the result toward simpler stacks and managed services.",
  },
];

module.exports = {
  questionnaire,
};
