export const defaultValues = {
  projectName: "",
  projectStage: "idea",
  businessType: "saas",
  targetRegion: "north-america",
  deploymentPreference: "managed-cloud",
  monthlyUsers: 500,
  monthlyBudget: 150,
  applicationType: "web-app",
  preferredStackFamily: "no-preference",
  coreFeatures: ["authentication"],
  realtimeFeatures: false,
  dataSensitivity: "low",
  availabilityRequirement: "basic",
  requiresDisasterRecovery: false,
  requiresComplianceTracking: false,
  needsTwentyFourSevenSupport: false,
  incidentResponseHours: 24,
  expectedGrowth: "slow",
  teamTechnicalLevel: "medium",
  needFastDelivery: true,
  teamMembers: [],
};
